# Generated by Django 3.0.8 on 2020-07-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
    ]
