# Generated by Django 3.0.8 on 2020-07-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_media_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(null=True, verbose_name='Phone Number'),
        ),
    ]
