# Generated by Django 3.0.8 on 2020-07-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200730_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
