# Generated by Django 3.0.8 on 2020-07-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200730_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(blank=True, default='/dummy.png', null=True, upload_to='teacher_image', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='teacher_video', verbose_name='Teacher Video'),
        ),
    ]
