# Generated by Django 3.0.8 on 2020-07-30 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200730_1119'),
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(blank=True, default='/dummy.png', null=True, upload_to='teacher-document', verbose_name='Certificate Record')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='Teacher')),
            ],
        ),
    ]
