# Generated by Django 3.0.8 on 2020-07-30 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_specializations'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
