# Generated by Django 3.0.8 on 2020-07-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_auto_20200730_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='teacherdocument',
            name='certificate',
            field=models.FileField(blank=True, default='/dummy.png', null=True, upload_to='teacher_document', verbose_name='Certificate Record'),
        ),
    ]
