# Generated by Django 3.0.8 on 2020-07-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_auto_20200730_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
    ]
