# Generated by Django 3.0.8 on 2020-07-30 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurations', '0008_ratings_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicgenre',
            options={'verbose_name': 'Music Genre', 'verbose_name_plural': 'Music Genres'},
        ),
        migrations.AlterField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
